### PR TITLE
Added disable Jiggle when is connected to wifi based on ssid/bssid inserted in textfield

### PR DESCRIPTION
**Pull request by ayazhussein**
Hi,
this is my first attempt to edit an Objective-c project.
I added this setting as I thought it might be useful for some people.

### CODE REVIEW

**Comment by bhaller** [comment]
Hi!  I am presently on vacation, and will be swamped with work for a while when I get back.  I will look at this, but it may take me a while to get to it – Jiggler is not a priority for me right now.  Thanks!

Cheers,

Ben Haller
Stick Software

**Comment by bhaller** [comment]
Is there a reason you closed this?

**Comment by ayazhussein** [comment]
No, I'll reopen 😄

**Comment by bhaller** [comment]
I will get to it some day, I'm just very busy lately :->

**Comment by ayazhussein** [comment]
No problem :D

**Pull request closed without merging**
